// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCguGh_u4BK371dJYTpk7MEi-Ih3pMQI',
    appId: '1:424182117489:web:eb5555b2b71369b24457d0',
    messagingSenderId: '424182117489',
    projectId: 'thriftnest-27ad6',
    authDomain: 'thriftnest-27ad6.firebaseapp.com',
    storageBucket: 'thriftnest-27ad6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkO1p1N76omCGmO3ScPpEA96_4NtiwJs',
    appId: '1:424182117489:android:3bf8f486acf3325f4457d0',
    messagingSenderId: '424182117489',
    projectId: 'thriftnest-27ad6',
    storageBucket: 'thriftnest-27ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsEJSkpXaLEIm42YBveX6MU8-PRZ_-OIo',
    appId: '1:424182117489:ios:ff1382de1003fe8b4457d0',
    messagingSenderId: '424182117489',
    projectId: 'thriftnest-27ad6',
    storageBucket: 'thriftnest-27ad6.firebasestorage.app',
    iosBundleId: 'com.example.thirftNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsEJSkpXaLEIm42YBveX6MU8-PRZ_-OIo',
    appId: '1:424182117489:ios:ff1382de1003fe8b4457d0',
    messagingSenderId: '424182117489',
    projectId: 'thriftnest-27ad6',
    storageBucket: 'thriftnest-27ad6.firebasestorage.app',
    iosBundleId: 'com.example.thirftNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvCguGh_u4BK371dJYTpk7MEi-Ih3pMQI',
    appId: '1:424182117489:web:e2b3ccad2c151e9c4457d0',
    messagingSenderId: '424182117489',
    projectId: 'thriftnest-27ad6',
    authDomain: 'thriftnest-27ad6.firebaseapp.com',
    storageBucket: 'thriftnest-27ad6.firebasestorage.app',
  );

}